### ISSUE TITLE
Add a CI with Git actions

### ISSUE THREAD

**Issue by fabiencelier** [fabiencelier/universions#4]
Use git actions CI to test the PRs.

**Comment by Kineolyan** [comment]
As part of #15 , I wanted to change _test.yaml_ to run it on PRs. But only owners and members of the project can do so.
Here is the change I propose:
```diff
- on: [push]
+  push:
+    branches:
+      - master
+  pull_request:
+    branches:
+      - master
```

**Comment by fabiencelier** [comment]
I have added that and PR now requires the tests to pass.

I guess I can close this ticket
