### ISSUE TITLE
write and release sphinx documentation

### ISSUE THREAD

**Issue by fabiencelier** [fabiencelier/universions#7]

**Comment by Kineolyan** [comment]
I already see some documentation. How much is it close to your expectations?
I see for example that we are missing at least a small page for the CLI, listing the only available options. Otherwise, it seems ok

**Comment by Kineolyan** [comment]
Moreover, #17 is stating that workflows already take care of deploying the doc

**Comment by fabiencelier** [comment]
There is a bug in the documentation build and the doc of functions are displayed correctly.

The documentation is built by readthedoc when a commit is merged on master, I need to learn how to fix that

**Comment by fabiencelier** [comment]
I have fixed it from the readthedocs.io interface
